### PR TITLE
Eliminate Handlebars.compile for eui-month

### PR DESCRIPTION
**Pull request by artsyca**
Trying to eliminate the need for Handlebars.compile.
This PR doesn't really integrate with HTMLBars with regards to returning DOM but at least it eliminates a pretty heavy dependency.

### CODE REVIEW

**Comment by elucid** [comment]
Hey there. First off the replacement isn't xss safe--you would need an escape for at least the class names but realistically all 3.

Second, although this looks like a runtime dependency on 'Handlebars.compile' it actually isn't. You can take a look at https://github.com/emberui/emberui/commit/dd9eb3877b64ccabcf2d6359e4da54fc4d78a2b4 for more details but the gist is that the template is precompiled at build time and 'Handlebars.compile' doesn't actually exist at runtime.

**Comment by artsyca** [comment]
Hey @elucid Thanks for the pointer, I did see the `precompileTemplate` being expanded in the final output and now you've shown me where it all comes together.

The reason for this whole thing is that somewhere in more recent version of Ember.Handlebars the format for calling a template has changed and we're getting an error `object is not a function` because now it seems `DATE_SLOT_HBS` is not a function any more but rather `DATE_SLOT_HBS.main`. To add more complications, it also seems to accept a different format of parameters than before.

I guess this PR was just my attempt at short-circuiting the need to understand all of the handlebars internals. I totally understand that it can't be merged but is there any way we can make it work with  Ember > 1.7?

**Comment by jacojoubert** [comment]
Right now emberui works with 1.8.1. I will be doing a big upgrade once ember stabilizes to get it working with htmlbars.

**Comment by artsyca** [comment]
Thanks @jacojoubert.

**Comment by jacojoubert** [comment]
I just did a clean install of my app using ember 1.8.1 and it does have issues because of list-view. I have a locally built version that fixes it. I will have to look where list-view stands in terms of compatibility. Hopefully with the Glimmer engine we can just eliminate the need for list-view altogether.

**Comment by elucid** [comment]
Based on the EmberConf keynote I don't think that ListView is going away but rather will become a first-class citizen in the ember ecosystem.

Currently there is a stand-in ember-cli addon (https://github.com/mysterlune/ember-cli-list-view) that does this but it is supposed to be moved under the ember-cli org sometime in the near future. See https://github.com/emberjs/list-view/issues/160#issuecomment-68886646 for more info.
